name: Bot

on:
  schedule:
    # At 23:00 on every day-of-week from Monday through Friday
    # but 19:00 in Wall st., NY
    - cron: '0 23 * * 1-5'
  workflow_dispatch:
    inputs:
      updateNow:
        description: 'Update'
        required: true
        default: 'Run forced'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install python package
      run: |
        pip -r install requirements.txt

    - name: Run bot
      run: |
        python ./stocker.py

    - name: Commit report
      run: |
          git config user.name 'Github Actions'
          git config user.email 'joo-na@users.noreply.github.com'
          git add README.md *.json
          git commit -m ":chart_with_upwards_trend: updated on $(echo `date "+%Y-%m-%d"`)"
          git push
