name: Bot

on:
  schedule:
    # At 23:00 on every day-of-week from Monday through Friday
    - cron: '0 23 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install python package
      run: |        
        pip install requests
        pip install bs4

    - name: Run bot
    - run: |
        python ./stocker.py

    - name: Commit report
      run: |
          git config --global user.name 'joonas-bot'
          git config --global user.email 'joonas-yoon@users.noreply.github.com'
          git add README.md
          git commit -m ":chart_with_upwards_trend: updated on $(echo `date "+%Y-%m-%d"`)"
