name: Bot

on:
  schedule:
    # every 4:00 am, MON/WED/FRI (UTC+9)
    # but 7:00 pm, SUN/TUE/THU in UTC
    - cron: '0 19 * * 0,2,4'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install python package
      run: |        
        pip install requests
        pip install bs4

    - name: Run bot
    - run: |
        python ./stocker.py

    - name: Commit report
      run: |
          git config --global user.name 'joonas-bot'
          git config --global user.email 'joonas-yoon@users.noreply.github.com'
          git add README.md