name: Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get changes
        run: |
          git config --global user.name 'joonas-bot'
          git config --global user.email 'joonas-yoon@users.noreply.github.com'
          cp README.md _README.md

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Build GitHub Pages
        run: |
          mv _README.md index.md
          git add index.md
          git commit -m "update index.md"
          git push
