name: Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Build GitHub Pages
        run: |
          git config --global user.name 'joonas-bot'
          git config --global user.email 'joonas-yoon@users.noreply.github.com'
          wget https://raw.githubusercontent.com/joonas-yoon/stocker/main/README.md
          mv README.md index.md
          git add -N index.md
          git diff index.md > git.diff
          [ -s git.diff ] && git add index.md && git commit -m "update index.md" && git push || echo "Skip commit"
